apiVersion: v1
data:
  SVC_HOST: x.36
  SVC_PASSWORD: xxx
  SVC_USERNAME: xxx
kind: Secret
metadata:
  creationTimestamp: "2026-06-27T19:10:13Z"
  name: nexus-svc-credentials
  namespace: nexus-system
  resourceVersion: "21571220"
  uid: 6305ee26-263f-4574-b2ee-202cc3d3e77d
type: Opaque