apiVersion: v1
data:
  GEMINI_API_KEY: XXX
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"nexus-gemini-secret","namespace":"kagent"},"stringData":{"GEMINI_API_KEY":"XXX"},"type":"Opaque"}
  creationTimestamp: "2026-06-28T09:19:51Z"
  name: nexus-gemini-secret
  namespace: kagent
  resourceVersion: "21800707"
  uid: eecf890d-56b5-4dc8-9d37-1f3f7a4f3b4f
type: Opaque